name: CI

on:
- push
- pull_request

jobs:
  build_deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        check-latest: true
    - name: Build
      run: node_modules/.bin/hexo g
    - name: Inject Service Worker
      uses: Menci/service-worker-redirect-origin@main
      with:
        www-root: public
        target-base-url: https://cdn-static.menci.xyz/menci-oi-blog/
    - name: Push to GitHub
      id: commit-push
      if: ${{ github.event_name == 'push' }}
      run: |
        touch public/404.html
        git config --global user.name $(git show -s --format='%an' HEAD)
        git config --global user.email $(git show -s --format='%ae' HEAD)
        eval `ssh-agent -s`
        echo "$SSH_KEY" | tr -d '\r' | ssh-add -
        node_modules/.bin/hexo d

        cd .deploy_git
        echo "::set-output commit-hash=$(git rev-parse HEAD)"
      env:
        SSH_KEY: ${{ secrets.DEPLOY_KEY_TARGET }}
    - name: Wait for Cloudflare Pages Deployment
      if: ${{ github.event_name == 'push' }}
      uses: Menci/cf-pages-await@main
      with:
        accountEmail: ${{ secrets.CLOUDFLARE_ACCOUNT_EMAIL }}
        apiKey: ${{ secrets.CLOUDFLARE_API_KEY }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        project: menci-oi-blog
        commitHash: ${{ steps.commit-push.outputs.commit-hash }}
    - name: Deploy to Static CDN
      uses: AyaInfra/StaticCDNDeploy@main
      with:
        deploy-credentials: ${{ secrets.STATIC_CDN_CREDENTIALS }}
        local-path: public
        remote-path: menci-oi-blog
    - name: Deploy to Azure
      if: ${{ github.event_name == 'push' }}
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        action: upload
        app_location: /public
        skip_app_build: true
    - name: Submit Sitemap
      uses: atymic/sitemap-ping-action@master
      with:
        sitemap-url: https://oi.men.ci/sitemap.xml
