name: CI

on:
- push
- pull_request

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        check-latest: true
    - name: Install pygments
      run: sudo apt-get update && sudo apt-get install -y python3-pygments
    - name: Build
      run: node_modules/.bin/hexo g
    - name: Deploy
      uses: Azure/static-web-apps-deploy@v1
      if: ${{ github.event_name == 'push' }}
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        action: upload
        app_location: /public
        skip_app_build: true
