name: CI

on:
- push
- pull_request

env:
  CI: true

jobs:
  build_deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        check-latest: true
    - name: Build
      run: node_modules/.bin/hexo g
    - name: Push to GitHub
      if: ${{ github.event_name == 'push' }}
      run: |
        touch public/404.html
        git config --global user.name $(git show -s --format='%an' HEAD)
        git config --global user.email $(git show -s --format='%ae' HEAD)
        sed -i "s#ssh://git@github.com#https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com#" _config.yml
        node_modules/.bin/hexo d
    - name: Deploy to Azure
      uses: Azure/static-web-apps-deploy@v1
      if: ${{ github.event_name == 'push' }}
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        action: upload
        app_location: /public
        skip_app_build: true
